version: "3"

services:

  worker:
    build: .
    command: python3.6 manage.py runworker websocket
    volumes:
      - .:/iowaidea
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SERVER_ENV: ${SERVER_ENV}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      RAVEN_DSN: ${RAVEN_DSN}
      REDIS_URL: ${REDIS_URL}

  huey_worker:
    build: .
    command: python3.6 manage.py run_huey
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SERVER_ENV: ${SERVER_ENV}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      RAVEN_DSN: ${RAVEN_DSN}
      REDIS_URL: ${REDIS_URL}
    volumes:
      - .:/iowaidea

  web:
    build: .
    command: sh -c  "python3.6 manage.py migrate && daphne -b 0.0.0.0 -p 8000 iowaidea.asgi:application"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SERVER_ENV: ${SERVER_ENV}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      RAVEN_DSN: ${RAVEN_DSN}
      REDIS_URL: ${REDIS_URL}
    volumes:
      - .:/iowaidea
    ports:
      - "8000:8000"
